// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:1cc398dc-1112-46f9-9eea-3f8616e536ad';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'hello-hosting-mobilehub-815028778';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd1hler0ldsoho2.cloudfront.net';
var aws_mobile_analytics_app_id = '6173039c421f4d5489301a1472ac37f1';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '38e63cd4-e75e-4671-b96a-2742f92edd1d';
var aws_project_name = 'hello';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'hello-mobilehub-815028778';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
