// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:1cc398dc-1112-46f9-9eea-3f8616e536ad',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'hello-hosting-mobilehub-815028778',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1hler0ldsoho2.cloudfront.net',
    'aws_mobile_analytics_app_id': '6173039c421f4d5489301a1472ac37f1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '38e63cd4-e75e-4671-b96a-2742f92edd1d',
    'aws_project_name': 'hello',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'hello-mobilehub-815028778',
}

export default awsmobile;
